[tool.poetry]
name = "diabeteswarrior"
version = "0.1.0"
description = "Diabetes Management Application"
authors = ["Harrison Johnson <hjohnson933@cox.net>"]
license = "OSLv3.0"

[tool.poetry.dependencies]
python = "^3.9"
arrow = "^1.2.2"
Flask = "^2.0.2"
Flask-WTF = "^1.0.0"
Flask-Bootstrap = "^3.3.7"
email-validator = "^1.1.3"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
