[tool.poetry]
name = "diabeteswarrior"
version = "0.1.0"
description = "Diabetes Management Application"
authors = ["Harrison Johnson <hjohnson933@cox.net>"]

[tool.poetry.dependencies]
python = ">=3.9,<3.11" 
pandas = "^1.3.5"
numpy = "^1.21.5"
arrow = "^1.2.1"
tasklib = "^2.4.3"
prompt-toolkit = "^3.0.26"
Pygments = "^2.11.1"
ipykernel = "^6.6.0"
measurement = "^3.2.0"
matplotlib = "^3.5.1"
dash = "^2.0.0"
dash-bootstrap-components = "^1.0.2"
Flask = "^2.0.2"
pytest = "^7.0.0"
report = "^0.0.1"

[tool.poetry.dev-dependencies]
pylint = "^2.12.2"
flake8 = "^4.0.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
