[tool.poetry]
name = "diabeteswarrior"
version = "0.1.0"
description = "Diabetes Managment Application"
authors = ["Harrison Johnson <hjohnson933@cox.net>"]
license = "OSLv3.0"

[tool.poetry.dependencies]
python = "^3.9"
arrow = "^1.2.2"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
