[tool.poetry]
name = "diabeteswarrior"
version = "0.1.0"
description = "Diabetes Management Application"
authors = ["Harrison Johnson <hjohnson933@cox.net>"]
license = "OSLv3.0"

[tool.poetry.dependencies]
python = "^3.9"
arrow = "^1.2.2"
Flask = "^2.0.2"
Flask-Login = "^0.5.0"
Flask-SQLAlchemy = "^2.5.1"
Flask-Migrate = "^3.1.0"
Flask-WTF = "^1.0.0"
dash = "^2.1.0"
pandas-datareader = "^0.10.0"
gunicorn = "^20.1.0"
python-dotenv = "^0.19.2"
alembic = "^1.7.6"
attrs = "^21.4.0"
certifi = "^2021.10.8"
chardet = "^4.0.0"
click = "^8.0.3"
dash-core-components = "^2.0.0"
dash-html-components = "^2.0.0"
dash-renderer = "^1.9.1"
dash-table = "^5.0.0"
decorator = "^5.1.1"
Flask-Compress = "^1.10.1"
future = "^0.18.2"
idna = "^3.3"
ipython_genutils = "^0.2.0"
itsdangerous = "^2.0.1"
Jinja2 = "^3.0.3"
jsonschema = "^4.4.0"
jupyter-core = "^4.9.1"
lxml = "^4.7.1"
Mako = "^1.1.6"
MarkupSafe = "^2.0.1"
nbformat = "^5.1.3"
numpy = "^1.22.2"
pandas = "^1.4.0"
plotly = "^5.6.0"
pyrsistent = "^0.18.1"
python-dateutil = "^2.8.2"
python-editor = "^1.0.4"
pytz = "^2021.3"
requests = "^2.27.1"
retrying = "^1.3.3"
six = "^1.16.0"
SQLAlchemy = "^1.4.31"
traitlets = "^5.1.1"
urllib3 = "^1.26.8"
Werkzeug = "^2.0.3"
wrapt = "^1.13.3"
WTForms = "^3.0.1"

[tool.poetry.dev-dependencies]
flake8 = "^4.0.1"
isort = "^5.10.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
