[tool.poetry]
name = "diabeteswarrior"
version = "0.1.0"
description = "Diabetes Management Application"
authors = ["Harrison Johnson <hjohnson933@cox.net>"]
license = "OSLv3.0"

[tool.poetry.dependencies]
python = "^3.9"
arrow = "^1.2.2"
Flask = "^2.0.2"
Flask-Login = "^0.5.0"
Flask-SQLAlchemy = "^2.5.1"
Flask-Migrate = "^3.1.0"
Flask-WTF = "^1.0.0"
dash = "^2.1.0"
pandas-datareader = "^0.10.0"
gunicorn = "^20.1.0"
python-dotenv = "^0.19.2"

[tool.poetry.dev-dependencies]
flake8 = "^4.0.1"
isort = "^5.10.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
