"""Meal Dash Application Layout"""
import arrow
import dash_bootstrap_components as dbc
from dash import dcc, html

from .assets.utils import dropdown_input, form_buttons, user_input

BTN_DICT = {
    'scope': ['Last 24 hours', 'Last 14 days', 'Last 90 days'],
    'food-unit': [{'label': 'Cup', 'value': 'c'},
                  {'label': 'Fluid ounce', 'value': 'fl oz'},
                  {'label': 'Gallon', 'value': 'gal'},
                  {'label': 'Milliliter', 'value': 'ml'},
                  {'label': 'Liter', 'value': 'l'},
                  {'label': 'Pint', 'value': 'pt'},
                  {'label': 'Quart', 'value': 'qt'},
                  {'label': 'Tablespoon', 'value': 'tbsp'},
                  {'label': 'Teaspoon', 'value': 'tsp'},
                  {'label': 'Gram', 'value': 'g'},
                  {'label': 'Kilogram', 'value': 'kg'},
                  {'label': 'Pound', 'value': 'lb'},
                  {'label': 'Milligram', 'value': 'mg'},
                  {'label': 'Ounce', 'value': 'oz'},
                  {'label': 'Dozen', 'value': 'doz'},
                  {'label': 'Large', 'value': 'lg'},
                  {'label': 'Pinch', 'value': 'p'},
                  {'label': 'Package', 'value': 'pkg'},
                  {'label': 'Small', 'value': 'sm'},
                  {'label': 'Speck', 'value': 'sp'},
                  {'label': 'Slice', 'value': 'sl'}]
}


layout = html.Div(
    id='main',
    className='container-xl',
    children=[
        dcc.Store(id='user-store'),
        html.H1(id='username'),
        html.H1(id='meal-food', children='Meals and Food Data'),
        dropdown_input(name='scope',
            className='meal',
            value='Last 24 hours',
            btn_dict=BTN_DICT),
        html.Br(),
        dbc.Form(id='meal',
            children=[
                user_input(name='meal-timetamp',
                    className='meal',
                    type='text',
                    placeholder='Date & Time.',
                    required=False,
                    value=arrow.now().format("YYYY-MM-DD HH:mm")),
                user_input(name='meal-calories',
                    className='meal',
                    type='number',
                    placeholder='Calories',
                    required=False,
                    value=None),
                user_input(name='meal-fat',
                    className='meal',
                    type='number',
                    placeholder='Fat',
                    required=False,
                    value=None),
                user_input(name='meal-cholesterol',
                    className='meal',
                    type='number',
                    placeholder='Cholesterol',
                    required=False,
                    value=None),
                user_input(name='meal-sodium',
                    className='meal',
                    type='number',
                    placeholder='Sodium',
                    required=False,
                    value=None),
                user_input(name='meal-carbohydrate',
                    className='meal',
                    type='number',
                    placeholder='Carbohydrate',
                    required=False,
                    value=None),
                user_input(name='meal-protein',
                    className='meal',
                    type='number',
                    placeholder='Protein',
                    required=False,
                    value=None),
                user_input(name='meal-servings',
                    className='meal',
                    type='text',
                    placeholder='Servings',
                    required=False,
                    value=None),
                user_input(name='meal-indices',
                    className='meal',
                    type='text',
                    placeholder='Indices',
                    required=False,
                    value=None),
                form_buttons(name='submit-meal',
                    className='meal',
                    children='Submit Meal')
            ]
        ),
        html.Br(),
        dbc.Form(id='food',
            children=[
                user_input(name='food-timetamp',
                    className='food',
                    type='text',
                    placeholder='Date & Time.',
                    required=False,
                    value=arrow.now().format("YYYY-MM-DD HH:mm")),
                user_input(name='food-domain',
                    className='food',
                    type='text',
                    placeholder='Domain',
                    required=True,
                    value=None),
                user_input(name='food-name',
                    className='food',
                    type='text',
                    placeholder='Name',
                    required=True,
                    value=None),
                user_input(name='food-portion',
                    className='food',
                    type='text',
                    placeholder='Portions',
                    required=False,
                    value=None),
                dropdown_input(name='food-unit',
                    className='food',
                    value='g',
                    btn_dict=BTN_DICT),
                user_input(name='food-calories',
                    className='food',
                    type='number',
                    placeholder='Calories',
                    required=True,
                    value=None),
                user_input(name='food-fat',
                    className='food',
                    type='number',
                    placeholder='Fat',
                    required=True,
                    value=None),
                user_input(name='food-cholesterol',
                    className='food',
                    type='number',
                    placeholder='Cholesterol',
                    required=True,
                    value=None),
                user_input(name='food-sodium',
                    className='food',
                    type='number',
                    placeholder='Sodium',
                    required=True,
                    value=None),
                user_input(name='food-carbohydrate',
                    className='food',
                    type='number',
                    placeholder='Carbohydrate',
                    required=True,
                    value=None),
                user_input(name='food-protein',
                    className='food',
                    type='number',
                    placeholder='Protein',
                    required=True,
                    value=None),
                form_buttons(name='submit-food',
                    className='food',
                    children='Submit Food')
            ]
        ),
        html.Br(),
        html.P('food_table()')
    ]
)
