"""Meal Dash Application Layout"""
from tkinter import N
import arrow
import dash_bootstrap_components as dbc
from dash import dcc, html

from .assets.utils import dropdown_input, form_buttons, user_input

BTN_DICT = {
    'scope': ['Last 24 hours', 'Last 14 days', 'Last 90 days'],
    'unit': [
        {'label': 'Cup', 'value': 'c'},
        {'label': 'Fluid ounce', 'value': 'fl oz'},
        {'label': 'Gallon', 'value': 'gal'},
        {'label': 'Milliliter', 'value': 'ml'},
        {'label': 'Liter', 'value': 'l'},
        {'label': 'Pint', 'value': 'pt'},
        {'label': 'Quart', 'value': 'qt'},
        {'label': 'Tablespoon', 'value': 'tbsp'},
        {'label': 'Teaspoon', 'value': 'tsp'},
        {'label': 'Gram', 'value': 'g'},
        {'label': 'Kilogram', 'value': 'kg'},
        {'label': 'Pound', 'value': 'lb'},
        {'label': 'Milligram', 'value': 'mg'},
        {'label': 'Ounce', 'value': 'oz'},
        {'label': 'Dozen', 'value': 'doz'},
        {'label': 'Large', 'value': 'lg'},
        {'label': 'Pinch', 'value': 'p'},
        {'label': 'Package', 'value': 'pkg'},
        {'label': 'Small', 'value': 'sm'},
        {'label': 'Speck', 'value': 'sp'},
        {'label': 'Slice', 'value': 'sl'}
    ]
}


layout = html.Div(
    id='main',
    className='container-xl',
    children=[
        dcc.Store(id='user-store'),
        html.H1(id='username'),
        html.H1(id='meal-food', children='Meals and Food Data'),
        dropdown_input(name='scope',
            className='meal',
            value='Last 24 hours',
            btn_dict=BTN_DICT),
        html.Br(),
        dbc.Form(id='meal',
            children=[
                user_input(name='meal-timetamp',
                    className='meal',
                    type='text',
                    placeholder='Date & Time.',
                    required=False,
                    value=arrow.now().format("YYYY-MM-DD HH:mm")),
                html.P('...'),
                form_buttons(name='submit-meal',
                    className='meal',
                    children='Submit Meal')
            ]
        ),
        html.Br(),
        dbc.Form(id='food',
            children=[
                user_input(name='food-timetamp',
                    className='food',
                    type='text',
                    placeholder='Date & Time.',
                    required=False,
                    value=arrow.now().format("YYYY-MM-DD HH:mm")),
                user_input(name='domain-food',
                    className='food',
                    type='text',
                    placeholder='Domain',
                    required=True,
                    value=None),
                user_input(name='name-food',
                    className='food',
                    type='text',
                    placeholder='Name',
                    required=True,
                    value=None),
                user_input(name='portion',
                    className='food',
                    type='text',
                    placeholder='Portions',
                    required=False,
                    value=None),
                dropdown_input(name='unit',
                    className='food',
                    value='g',
                    btn_dict=BTN_DICT),
                user_input(name='calories',
                    className='food',
                    type='number',
                    placeholder='Calories',
                    required=True,
                    value=None),
                user_input(name='fat',
                    className='food',
                    type='number',
                    placeholder='Fat',
                    required=True,
                    value=None),
                user_input(name='cholesterol',
                    className='food',
                    type='number',
                    placeholder='Cholesterol',
                    required=True,
                    value=None),
                user_input(name='sodium',
                    className='food',
                    type='number',
                    placeholder='Sodium',
                    required=True,
                    value=None),
                user_input(name='carbohydrate',
                    className='food',
                    type='number',
                    placeholder='Carbohydrate',
                    required=True,
                    value=None),
                user_input(name='protein',
                    className='food',
                    type='number',
                    placeholder='Protein',
                    required=True,
                    value=None),
                form_buttons(name='submit-food',
                    className='food',
                    children='Submit Food')
            ]
        ),
        html.Br(),
        html.P('food_table()')
    ]
)
